import Head from "next/head";
import { Poppins } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useMemo } from "react";
import numToStr from "@/helpers/numConvert";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  const [input, setInput] = useState("");
  function handleChange(e) {
    setInput(e.target.value);
  }

  const answer = numToStr(input);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className} ${styles.main}`}>
        <h1 className={`${poppins.className} ${styles.h1}`}>Enter a Number</h1>
        <form className={styles.form}>
          <input
            className={`${poppins.className} ${styles.input}`}
            type="number"
            onChange={handleChange}
            value={input}
          />
        </form>
        <h2 className={`${poppins.className} ${styles.h2}`}>{answer}</h2>

        <svg
          className={`${poppins.className} ${styles.svg}`}
          xmlns="http://www.w3.org/2000/svg"
          width="100%"
          height="100%"
          viewBox="0 0 300 24"
        >
          <text textLength="290" lengthAdjust="spacing" x="5" y="14">
            {answer}
          </text>
        </svg>
      </main>
    </>
  );
}
